import { JuzMeta } from '../types';

export const JUZ_CATALOG: JuzMeta[] = [
  {
    number: 1,
    nameAr: 'الجزء الأول (الم)',
    nameEn: 'Juz 1 (Alif Lam Meem)',
    shortNameAr: 'الم',
    startPage: 1,
    endPage: 21,
    startSurahNumber: 1,
    startAyahNumber: 1,
    surahsIncluded: ['الفاتحة', 'البقرة (1-141)'],
    surahsIncludedEn: ['Al-Fatihah', 'Al-Baqarah (1-141)'],
    totalAyahs: 148,
  },
  {
    number: 2,
    nameAr: 'الجزء الثاني (سيقول)',
    nameEn: 'Juz 2 (Sayaqool)',
    shortNameAr: 'سيقول',
    startPage: 22,
    endPage: 41,
    startSurahNumber: 2,
    startAyahNumber: 142,
    surahsIncluded: ['البقرة (142-252)'],
    surahsIncludedEn: ['Al-Baqarah (142-252)'],
    totalAyahs: 111,
  },
  {
    number: 3,
    nameAr: 'الجزء الثالث (تلك الرسل)',
    nameEn: 'Juz 3 (Tilkar Rusul)',
    shortNameAr: 'تلك الرسل',
    startPage: 42,
    endPage: 61,
    startSurahNumber: 2,
    startAyahNumber: 253,
    surahsIncluded: ['البقرة (253-286)', 'آل عمران (1-92)'],
    surahsIncludedEn: ['Al-Baqarah (253-286)', 'Ali \'Imran (1-92)'],
    totalAyahs: 126,
  },
  {
    number: 4,
    nameAr: 'الجزء الرابع (لن تنالوا)',
    nameEn: 'Juz 4 (Lan Tanaalu)',
    shortNameAr: 'لن تنالوا',
    startPage: 62,
    endPage: 81,
    startSurahNumber: 3,
    startAyahNumber: 93,
    surahsIncluded: ['آل عمران (93-200)', 'النساء (1-23)'],
    surahsIncludedEn: ['Ali \'Imran (93-200)', 'An-Nisa (1-23)'],
    totalAyahs: 131,
  },
  {
    number: 5,
    nameAr: 'الجزء الخامس (والمحصنات)',
    nameEn: 'Juz 5 (Wal Muhsanat)',
    shortNameAr: 'والمحصنات',
    startPage: 82,
    endPage: 101,
    startSurahNumber: 4,
    startAyahNumber: 24,
    surahsIncluded: ['النساء (24-147)'],
    surahsIncludedEn: ['An-Nisa (24-147)'],
    totalAyahs: 124,
  },
  {
    number: 6,
    nameAr: 'الجزء السادس (لا يحب الله)',
    nameEn: 'Juz 6 (La Yuhibbullah)',
    shortNameAr: 'لا يحب الله',
    startPage: 102,
    endPage: 121,
    startSurahNumber: 4,
    startAyahNumber: 148,
    surahsIncluded: ['النساء (148-176)', 'المائدة (1-81)'],
    surahsIncludedEn: ['An-Nisa (148-176)', 'Al-Ma\'idah (1-81)'],
    totalAyahs: 110,
  },
  {
    number: 7,
    nameAr: 'الجزء السابع (وإذا سمعوا)',
    nameEn: 'Juz 7 (Wa Iza Sami\'u)',
    shortNameAr: 'وإذا سمعوا',
    startPage: 122,
    endPage: 141,
    startSurahNumber: 5,
    startAyahNumber: 82,
    surahsIncluded: ['المائدة (82-120)', 'الأنعام (1-110)'],
    surahsIncludedEn: ['Al-Ma\'idah (82-120)', 'Al-An\'am (1-110)'],
    totalAyahs: 149,
  },
  {
    number: 8,
    nameAr: 'الجزء الثامن (ولو أننا)',
    nameEn: 'Juz 8 (Wa Law Annana)',
    shortNameAr: 'ولو أننا',
    startPage: 142,
    endPage: 161,
    startSurahNumber: 6,
    startAyahNumber: 111,
    surahsIncluded: ['الأنعام (111-165)', 'الأعراف (1-87)'],
    surahsIncludedEn: ['Al-An\'am (111-165)', 'Al-A\'raf (1-87)'],
    totalAyahs: 142,
  },
  {
    number: 9,
    nameAr: 'الجزء التاسع (قال الملأ)',
    nameEn: 'Juz 9 (Qal Al-Mala\')',
    shortNameAr: 'قال الملأ',
    startPage: 162,
    endPage: 181,
    startSurahNumber: 7,
    startAyahNumber: 88,
    surahsIncluded: ['الأعراف (88-206)', 'الأنفال (1-40)'],
    surahsIncludedEn: ['Al-A\'raf (88-206)', 'Al-Anfal (1-40)'],
    totalAyahs: 159,
  },
  {
    number: 10,
    nameAr: 'الجزء العاشر (واعلموا)',
    nameEn: 'Juz 10 (Wa\'lamoo)',
    shortNameAr: 'واعلموا',
    startPage: 182,
    endPage: 201,
    startSurahNumber: 8,
    startAyahNumber: 41,
    surahsIncluded: ['الأنفال (41-75)', 'التوبة (1-92)'],
    surahsIncludedEn: ['Al-Anfal (41-75)', 'At-Tawbah (1-92)'],
    totalAyahs: 127,
  },
  {
    number: 11,
    nameAr: 'الجزء الحادي عشر (يعتذرون)',
    nameEn: 'Juz 11 (Ya\'taziroon)',
    shortNameAr: 'يعتذرون',
    startPage: 202,
    endPage: 221,
    startSurahNumber: 9,
    startAyahNumber: 93,
    surahsIncluded: ['التوبة (93-129)', 'يونس', 'هود (1-5)'],
    surahsIncludedEn: ['At-Tawbah (93-129)', 'Yunus', 'Hud (1-5)'],
    totalAyahs: 151,
  },
  {
    number: 12,
    nameAr: 'الجزء الثاني عشر (وما من دابة)',
    nameEn: 'Juz 12 (Wa Ma Min Dabbah)',
    shortNameAr: 'وما من دابة',
    startPage: 222,
    endPage: 241,
    startSurahNumber: 11,
    startAyahNumber: 6,
    surahsIncluded: ['هود (6-123)', 'يوسف (1-52)'],
    surahsIncludedEn: ['Hud (6-123)', 'Yusuf (1-52)'],
    totalAyahs: 170,
  },
  {
    number: 13,
    nameAr: 'الجزء الثالث عشر (وما أبرئ)',
    nameEn: 'Juz 13 (Wa Ma Ubarri\'u)',
    shortNameAr: 'وما أبرئ',
    startPage: 242,
    endPage: 261,
    startSurahNumber: 12,
    startAyahNumber: 53,
    surahsIncluded: ['يوسف (53-111)', 'الرعد', 'إبراهيم'],
    surahsIncludedEn: ['Yusuf (53-111)', 'Ar-Ra\'d', 'Ibrahim'],
    totalAyahs: 155,
  },
  {
    number: 14,
    nameAr: 'الجزء الرابع عشر (ربما)',
    nameEn: 'Juz 14 (Rubama)',
    shortNameAr: 'ربما',
    startPage: 262,
    endPage: 281,
    startSurahNumber: 15,
    startAyahNumber: 1,
    surahsIncluded: ['الحجر', 'النحل'],
    surahsIncludedEn: ['Al-Hijr', 'An-Nahl'],
    totalAyahs: 227,
  },
  {
    number: 15,
    nameAr: 'الجزء الخامس عشر (سبحان الذي)',
    nameEn: 'Juz 15 (Subhan Allazi)',
    shortNameAr: 'سبحان الذي',
    startPage: 282,
    endPage: 301,
    startSurahNumber: 17,
    startAyahNumber: 1,
    surahsIncluded: ['الإسراء', 'الكهف (1-74)'],
    surahsIncludedEn: ['Al-Isra', 'Al-Kahf (1-74)'],
    totalAyahs: 185,
  },
  {
    number: 16,
    nameAr: 'الجزء السادس عشر (قال ألم)',
    nameEn: 'Juz 16 (Qala Alam)',
    shortNameAr: 'قال ألم',
    startPage: 302,
    endPage: 321,
    startSurahNumber: 18,
    startAyahNumber: 75,
    surahsIncluded: ['الكهف (75-110)', 'مريم', 'طه'],
    surahsIncludedEn: ['Al-Kahf (75-110)', 'Maryam', 'Ta-Ha'],
    totalAyahs: 269,
  },
  {
    number: 17,
    nameAr: 'الجزء السابع عشر (اقترب للناس)',
    nameEn: 'Juz 17 (Iqtaraba)',
    shortNameAr: 'اقترب',
    startPage: 322,
    endPage: 341,
    startSurahNumber: 21,
    startAyahNumber: 1,
    surahsIncluded: ['الأنبياء', 'الحج'],
    surahsIncludedEn: ['Al-Anbiya', 'Al-Hajj'],
    totalAyahs: 190,
  },
  {
    number: 18,
    nameAr: 'الجزء الثامن عشر (قد أفلح)',
    nameEn: 'Juz 18 (Qad Aflaha)',
    shortNameAr: 'قد أفلح',
    startPage: 342,
    endPage: 361,
    startSurahNumber: 23,
    startAyahNumber: 1,
    surahsIncluded: ['المؤمنون', 'النور', 'الفرقان (1-20)'],
    surahsIncludedEn: ['Al-Mu\'minun', 'An-Nur', 'Al-Furqan (1-20)'],
    totalAyahs: 202,
  },
  {
    number: 19,
    nameAr: 'الجزء التاسع عشر (وقال الذين)',
    nameEn: 'Juz 19 (Wa Qalallazina)',
    shortNameAr: 'وقال الذين',
    startPage: 362,
    endPage: 381,
    startSurahNumber: 25,
    startAyahNumber: 21,
    surahsIncluded: ['الفرقان (21-77)', 'الشعراء', 'النمل (1-55)'],
    surahsIncludedEn: ['Al-Furqan (21-77)', 'Ash-Shu\'ara', 'An-Naml (1-55)'],
    totalAyahs: 339,
  },
  {
    number: 20,
    nameAr: 'الجزء العشرون (فما كان جواب)',
    nameEn: 'Juz 20 (Amman Khalaqa)',
    shortNameAr: 'أمن خلق',
    startPage: 382,
    endPage: 401,
    startSurahNumber: 27,
    startAyahNumber: 56,
    surahsIncluded: ['النمل (56-93)', 'القصص', 'العنكبوت (1-45)'],
    surahsIncludedEn: ['An-Naml (56-93)', 'Al-Qasas', 'Al-\'Ankabut (1-45)'],
    totalAyahs: 171,
  },
  {
    number: 21,
    nameAr: 'الجزء الحادي والعشرون (اتل ما أوحي)',
    nameEn: 'Juz 21 (Utlu Ma Oohiya)',
    shortNameAr: 'اتل ما أوحي',
    startPage: 402,
    endPage: 421,
    startSurahNumber: 29,
    startAyahNumber: 46,
    surahsIncluded: ['العنكبوت (46-69)', 'الروم', 'لقمان', 'السجدة', 'الأحزاب (1-30)'],
    surahsIncludedEn: ['Al-\'Ankabut (46-69)', 'Ar-Rum', 'Luqman', 'As-Sajdah', 'Al-Ahzab (1-30)'],
    totalAyahs: 178,
  },
  {
    number: 22,
    nameAr: 'الجزء الثاني والعشرون (ومن يقنت)',
    nameEn: 'Juz 22 (Wa Man Yaqnut)',
    shortNameAr: 'ومن يقنت',
    startPage: 422,
    endPage: 441,
    startSurahNumber: 33,
    startAyahNumber: 31,
    surahsIncluded: ['الأحزاب (31-73)', 'سبأ', 'فاطر', 'يس (1-27)'],
    surahsIncludedEn: ['Al-Ahzab (31-73)', 'Saba', 'Fatir', 'Ya-Sin (1-27)'],
    totalAyahs: 169,
  },
  {
    number: 23,
    nameAr: 'الجزء الثالث والعشرون (وما أنزلنا)',
    nameEn: 'Juz 23 (Wa Maliya)',
    shortNameAr: 'وما لي',
    startPage: 442,
    endPage: 461,
    startSurahNumber: 36,
    startAyahNumber: 28,
    surahsIncluded: ['يس (28-83)', 'الصافات', 'ص', 'الزمر (1-31)'],
    surahsIncludedEn: ['Ya-Sin (28-83)', 'As-Saffat', 'Sad', 'Az-Zumar (1-31)'],
    totalAyahs: 357,
  },
  {
    number: 24,
    nameAr: 'الجزء الرابع والعشرون (فمن أظلم)',
    nameEn: 'Juz 24 (Fa Man Azlamu)',
    shortNameAr: 'فمن أظلم',
    startPage: 462,
    endPage: 481,
    startSurahNumber: 39,
    startAyahNumber: 32,
    surahsIncluded: ['الزمر (32-75)', 'غافر', 'فصلت (1-46)'],
    surahsIncludedEn: ['Az-Zumar (32-75)', 'Ghafir', 'Fussilat (1-46)'],
    totalAyahs: 175,
  },
  {
    number: 25,
    nameAr: 'الجزء الخامس والعشرون (إليه يرد)',
    nameEn: 'Juz 25 (Ilayhi Yuraddu)',
    shortNameAr: 'إليه يرد',
    startPage: 482,
    endPage: 501,
    startSurahNumber: 41,
    startAyahNumber: 47,
    surahsIncluded: ['فصلت (47-54)', 'الشورى', 'الزخرف', 'الدخان', 'الجاثية'],
    surahsIncludedEn: ['Fussilat (47-54)', 'Ash-Shura', 'Az-Zukhruf', 'Ad-Dukhan', 'Al-Jathiyah'],
    totalAyahs: 246,
  },
  {
    number: 26,
    nameAr: 'الجزء السادس والعشرون (حم)',
    nameEn: 'Juz 26 (Ha Meem / Al-Ahqaf)',
    shortNameAr: 'الأحقاف',
    startPage: 502,
    endPage: 521,
    startSurahNumber: 46,
    startAyahNumber: 1,
    surahsIncluded: ['الأحقاف', 'محمد', 'الفتح', 'الحجرات', 'ق', 'الذاريات (1-30)'],
    surahsIncludedEn: ['Al-Ahqaf', 'Muhammad', 'Al-Fath', 'Al-Hujurat', 'Qaf', 'Adh-Dhariyat (1-30)'],
    totalAyahs: 195,
  },
  {
    number: 27,
    nameAr: 'الجزء السابع والعشرون (قال فما خطبكم)',
    nameEn: 'Juz 27 (Qala Fama Khatbukum)',
    shortNameAr: 'الذاريات',
    startPage: 522,
    endPage: 541,
    startSurahNumber: 51,
    startAyahNumber: 31,
    surahsIncluded: ['الذاريات (31-60)', 'الطور', 'النجم', 'القمر', 'الرحمن', 'الواقعة', 'الحديد'],
    surahsIncludedEn: ['Adh-Dhariyat (31-60)', 'At-Tur', 'An-Najm', 'Al-Qamar', 'Ar-Rahman', 'Al-Waqi\'ah', 'Al-Hadid'],
    totalAyahs: 399,
  },
  {
    number: 28,
    nameAr: 'الجزء الثامن والعشرون (قد سمع الله)',
    nameEn: 'Juz 28 (Qad Sami\'a Allah)',
    shortNameAr: 'قد سمع',
    startPage: 542,
    endPage: 561,
    startSurahNumber: 58,
    startAyahNumber: 1,
    surahsIncluded: ['المجادلة', 'الحشر', 'الممتحنة', 'الصف', 'الجمعة', 'المنافقون', 'التغابن', 'الطلاق', 'التحريم'],
    surahsIncludedEn: ['Al-Mujadilah', 'Al-Hashr', 'Al-Mumtahanah', 'As-Saff', 'Al-Jumu\'ah', 'Al-Munafiqun', 'At-Taghabun', 'At-Talaq', 'At-Tahrim'],
    totalAyahs: 137,
  },
  {
    number: 29,
    nameAr: 'الجزء التاسع والعشرون (تبارك الذي)',
    nameEn: 'Juz 29 (Tabarak Allazi)',
    shortNameAr: 'تبارك',
    startPage: 562,
    endPage: 581,
    startSurahNumber: 67,
    startAyahNumber: 1,
    surahsIncluded: ['الملك', 'القلم', 'الحاقة', 'المعارج', 'نوح', 'الجن', 'المزمل', 'المدثر', 'القيامة', 'الإنسان', 'المرسلات'],
    surahsIncludedEn: ['Al-Mulk', 'Al-Qalam', 'Al-Haqqah', 'Al-Ma\'arij', 'Nuh', 'Al-Jinn', 'Al-Muzzammil', 'Al-Muddaththir', 'Al-Qiyamah', 'Al-Insan', 'Al-Mursalat'],
    totalAyahs: 431,
  },
  {
    number: 30,
    nameAr: 'الجزء الثلاثون (عم يتساءلون)',
    nameEn: 'Juz 30 (Amma Yatasa\'aloon)',
    shortNameAr: 'عم',
    startPage: 582,
    endPage: 604,
    startSurahNumber: 78,
    startAyahNumber: 1,
    surahsIncluded: ['النبأ', 'النازعات', 'عبس', 'التكوير', 'الانفطار', 'المطففين', 'الانشقاق', 'البروج', 'الطارق', 'الأعلى', 'الغاشية', 'الفجر', 'البلد', 'الشمس', 'الليل', 'الضحى', 'الشرح', 'التين', 'العلق', 'القدر', 'البينة', 'الزلزلة', 'العاديات', 'القارعة', 'التكاثر', 'العصر', 'الهمزة', 'الفيل', 'قريش', 'الماعون', 'الكوثر', 'الكافرون', 'النصر', 'المسد', 'الإخلاص', 'الفلق', 'الناس'],
    surahsIncludedEn: ['An-Naba', 'An-Nazi\'at', '\'Abasa', 'At-Takwir', 'Al-Infitar', 'Al-Mutaffifin', 'Al-Inshiqaq', 'Al-Buruj', 'At-Tariq', 'Al-A\'la', 'Al-Ghashiyah', 'Al-Fajr', 'Al-Balad', 'Ash-Shams', 'Al-Layl', 'Ad-Duha', 'Ash-Sharh', 'At-Tin', 'Al-\'Alaq', 'Al-Qadr', 'Al-Bayyinah', 'Az-Zalzalah', 'Al-\'Adiyat', 'Al-Qari\'ah', 'At-Takathur', 'Al-\'Asr', 'Al-Humazah', 'Al-Fil', 'Quraysh', 'Al-Ma\'un', 'Al-Kawthar', 'Al-Kafirun', 'An-Nasr', 'Al-Masad', 'Al-Ikhlas', 'Al-Falaq', 'An-Nas'],
    totalAyahs: 564,
  },
];
