import { SurahMeta, ReflectionCategory, ReflectionItem, Reciter } from '../types';

export const RECITERS: Reciter[] = [
  {
    id: 'ar.alafasy',
    name: 'Mishary Rashid Alafasy',
    arabicName: 'مشاري راشد العفاسي',
    subfolder: 'Alafasy_128kbps',
    serverKey: 'ar.alafasy',
  },
  {
    id: 'ar.husary',
    name: 'Mahmoud Khalil Al-Husary (Muallim / Educational)',
    arabicName: 'محمود خليل الحصري (معلم)',
    subfolder: 'Husary_128kbps',
    serverKey: 'ar.husary',
  },
  {
    id: 'ar.abdulbasitmurattal',
    name: 'Abdul Basit Murattal',
    arabicName: 'عبد الباسط عبد الصمد',
    subfolder: 'Abdul_Basit_Murattal_192kbps',
    serverKey: 'ar.abdulbasitmurattal',
  },
  {
    id: 'ar.shatri',
    name: 'Abu Bakr Al-Shatri',
    arabicName: 'أبو بكر الشاطري',
    subfolder: 'Abu_Bakr_Ash-Shaatree_128kbps',
    serverKey: 'ar.shaatree',
  },
  {
    id: 'ar.ghamadi',
    name: 'Saad Al-Ghamdi',
    arabicName: 'سعد الغامدي',
    subfolder: 'Ghamadi_40kbps',
    serverKey: 'ar.ghamadi',
  },
];

export const REFLECTION_CATEGORIES: ReflectionCategory[] = [
  {
    id: 'patience-grief',
    titleAr: 'الصبر والابتلاء والاحتساب',
    titleEn: 'Patience, Grief & Resilience',
    descriptionAr: 'آيات تسكب الطمأنينة على القلب المكلوم، وتعلّم الثبات واليقين عند نزول الشدائد وفقد الأحبة.',
    descriptionEn: 'Verses comforting the heavy heart, teaching steadfast endurance in moments of loss and hardship.',
    description: 'Verses comforting the heavy heart, teaching steadfast endurance in moments of loss and hardship.',
    iconName: 'Shield',
    color: 'from-amber-600 to-amber-800',
    accent: 'border-amber-500/30 text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-950/40',
  },
  {
    id: 'anxiety-peace',
    titleAr: 'السكينة وطمأنينة القلب',
    titleEn: 'Anxiety, Peace & Inner Calm',
    descriptionAr: 'تثبيتات ربانية تذهب الهلع والهم، وتملأ النفس سكينة بركونها إلى ذكر الله ومعيته.',
    descriptionEn: 'Divine reassurances that dissolve overwhelm, fear, and intrusive sorrow through His remembrance.',
    description: 'Divine reassurances that dissolve overwhelm, fear, and intrusive sorrow through His remembrance.',
    iconName: 'HeartHandshake',
    color: 'from-emerald-600 to-teal-800',
    accent: 'border-emerald-500/30 text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/40',
  },
  {
    id: 'repentance-hope',
    titleAr: 'التوبة والرجاء وسعة الرحمة',
    titleEn: 'Repentance, Hope & Divine Mercy',
    descriptionAr: 'بحر رحمة الله الواسع، وتذكير بأن العبد مهما قصر فإن باب التوبة والمغفرة مفتوح لا يغلق.',
    descriptionEn: 'The vast ocean of Allah’s infinite mercy, reminding us that no soul is ever beyond redemption.',
    description: 'The vast ocean of Allah’s infinite mercy, reminding us that no soul is ever beyond redemption.',
    iconName: 'Sparkles',
    color: 'from-blue-600 to-indigo-800',
    accent: 'border-blue-500/30 text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-950/40',
  },
  {
    id: 'guidance-purpose',
    titleAr: 'الهداية والتوكل واليقين',
    titleEn: 'Guidance, Tawakkul & Purpose',
    descriptionAr: 'آيات ترسيخ التوكل المطلق على الله وحده، ونيل البصيرة والفرقان عند اشتباه الطرق.',
    descriptionEn: 'Anchoring verses on relying solely upon Allah, finding clarity when paths seem uncertain.',
    description: 'Anchoring verses on relying solely upon Allah, finding clarity when paths seem uncertain.',
    iconName: 'Compass',
    color: 'from-rose-600 to-orange-800',
    accent: 'border-rose-500/30 text-rose-600 dark:text-rose-400 bg-rose-50 dark:bg-rose-950/40',
  },
  {
    id: 'quran-striving',
    titleAr: 'بركة القرآن وفضل مجاهدة الحفظ',
    titleEn: 'Quran Companionship & Hifz Devotion',
    descriptionAr: 'فضل مدارسة كتاب الله وتيسيره للحفظ والذكر، وعلو منزلة أهل القرآن وخاصته.',
    descriptionEn: 'The immense blessings of holding fast to the Quran, and divine facilitation for the memorizer.',
    description: 'The immense blessings of holding fast to the Quran, and divine facilitation for the memorizer.',
    iconName: 'BookOpen',
    color: 'from-purple-600 to-indigo-800',
    accent: 'border-purple-500/30 text-purple-600 dark:text-purple-400 bg-purple-50 dark:bg-purple-950/40',
  },
];

export const CURATED_REFLECTIONS: ReflectionItem[] = [
  // 1. Patience & Grief / الصبر والابتلاء
  {
    id: 'ref-1',
    categoryId: 'patience-grief',
    surahNumber: 2,
    surahNameAr: 'البقرة',
    surahNameEn: 'Al-Baqarah',
    ayahNumber: 155,
    ayahTextAr: 'وَلَنَبْلُوَنَّكُم بِشَيْءٍ مِّنَ الْخَوْفِ وَالْجُوعِ وَنَقْصٍ مِّنَ الْأَمْوَالِ وَالْأَنفُسِ وَالثَّمَرَاتِ ۗ وَبَشِّرِ الصَّابِرِينَ ۝ الَّذِينَ إِذَا أَصَابَتْهُم مُّصِيبَةٌ قَالُوا إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ',
    ayahTranslationEn: 'And We will surely test you with something of fear and hunger and a loss of wealth and lives and fruits, but give good tidings to the patient, who, when disaster strikes them, say, "Indeed we belong to Allah, and indeed to Him we will return."',
    ayahMeaningAr: 'الابتلاء سنة كونية لتطهير النفوس ورفع الدرجات؛ والاسترجاع (قول إنا لله وإنا إليه راجعون) إقرار بالعبودية لله والرجوع إليه.',
    contextAndTakeawayAr: 'الابتلاء ليس عقوبة بل مصفاة للمؤمن؛ حين تسلّم بأنك وما تملك ملكٌ لله تعالى، يزول الجزع وتتحول المصيبة إلى صلوات ورحمة وهداية من رب العالمين.',
    contextAndTakeawayEn: 'Hardship is an innate part of the earthly journey. Returning all things to Allah (Istirja\') transforms agony into elevated ranks and profound peace.',
    tafsirSummaryAr: 'قال ابن كثير: يخبر تعالى أنه يبتلي عباده بشيء من الشدائد ليتبين الصابر من الجازع. والمسترجعون جمعوا بين الإقرار بالعبودية لله والاعتراف بالبعث والجزاء.',
    tafsirSummaryEn: 'Ibn Kathir notes: Trials serve to purify the believer. The proclamation "Inna lillahi wa inna ilayhi raji\'un" acknowledges that our beings and possessions are trusts returning to their true Master.',
    tafsirSourceAr: 'تفسير ابن كثير',
    tafsirSourceEn: 'Tafsir Ibn Kathir',
    audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/162.mp3',
    tagsAr: ['الابتلاء', 'الصبر', 'الاسترجاع', 'البشارة'],
    tagsEn: ['Trials', 'Sabr', 'Good Tidings', 'Istirja'],
    tags: ['Trials', 'Bereavement', 'Sabr', 'Good Tidings'],
    contextAndTakeaway: 'Hardship is an innate part of the earthly journey. Returning all things to Allah transforms agony into elevated ranks.',
    tafsirSummary: 'Trials serve to purify the believer. The proclamation acknowledges all things belong to Allah.',
  },
  {
    id: 'ref-2',
    categoryId: 'patience-grief',
    surahNumber: 94,
    surahNameAr: 'الشرح',
    surahNameEn: 'Ash-Sharh',
    ayahNumber: 5,
    ayahTextAr: 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا ۝ إِنَّ مَعَ الْعُسْرِ يُسْرًا',
    ayahTranslationEn: 'For indeed, with hardship [will be] ease. Indeed, with hardship [will be] ease.',
    ayahMeaningAr: 'اقتران الفرج بالشدة اقتران مصاحبة لا انفصال؛ فلن يغلب عسرٌ واحد يُسرين عظيمين.',
    contextAndTakeawayAr: 'اليسر لا يأتي بعد العسر فحسب، بل يولد في رحمه ومعه جنباً إلى جنب. كل ضائقة في حفظك أو حياتك تحمل بذور التيسير والتوفيق الإلهي.',
    contextAndTakeawayEn: 'Ease is not merely coming after the hardship—it is intricately woven alongside it. One difficulty cannot overpower two manifestations of divine ease.',
    tafsirSummaryAr: 'قال السعدي: تعريف "العسر" وتنكير "اليسر" يدل على أن العسر واحد مهما تكرر، واليسر متعدد؛ فكلما اشتد الكرب كان الفرج أقرب وأعظم.',
    tafsirSummaryEn: 'Al-Saadi explains: The definite noun "al-\'Usr" repeated means a single trial, whereas the indefinite "yusra" signifies multiplied, endless divine ease unfolding simultaneously.',
    tafsirSourceAr: 'تفسير السعدي',
    tafsirSourceEn: 'Tafsir Al-Sa\'di',
    audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6095.mp3',
    tagsAr: ['الفرج', 'اليسر', 'الانشراح', 'الأمل'],
    tagsEn: ['Relief', 'Hope', 'Hardship to Ease', 'Optimism'],
    tags: ['Relief', 'Hope', 'Hardship to Ease'],
    contextAndTakeaway: 'Ease is intricately woven alongside hardship. One difficulty cannot overpower divine ease.',
    tafsirSummary: 'The repeated hardship represents one trial, while the ease is multiplied and encompassing.',
  },
  {
    id: 'ref-3',
    categoryId: 'patience-grief',
    surahNumber: 12,
    surahNameAr: 'يوسف',
    surahNameEn: 'Yusuf',
    ayahNumber: 86,
    ayahTextAr: 'قَالَ إِنَّمَا أَشْكُو بَثِّي وَحُزْنِي إِلَى اللَّهِ وَأَعْلَمُ مِنَ اللَّهِ مَا لَا تَعْلَمُونَ',
    ayahTranslationEn: 'He said, "I only complain of my suffering and my grief to Allah, and I know from Allah that which you do not know."',
    ayahMeaningAr: '{البث}: أشد الحزن الذي لا يطيق صاحبه كتمانه فيبثه وينشره؛ ويعقوب عليه السلام حصر شكواه إلى ربه دون الخلق.',
    contextAndTakeawayAr: 'أن تبث حزنك ودموعك في محراب السجود لله لا ينافي الصبر الجميل، بل هو عين التوحيد وقمة الأدب والافتقار إلى الحي القيوم.',
    contextAndTakeawayEn: 'Prophet Ya\'qub (AS) illustrates that venting raw sorrow to Allah is the pinnacle of Tawheed, never despairing of His reunion and grace.',
    tafsirSummaryAr: 'قال الطبري: أخبر يعقوب بنيه أنه لا يرجو كشف كربته إلا من القادر عليه، وعلمه برحمة ربه وحسن ظنه به يجعله موقناً بالإجابة والفرج القريب.',
    tafsirSummaryEn: 'Pouring grief out in private Du\'a to the Creator avoids the fragility of seeking human validation, maintaining unwavering good thoughts (Husn al-Dhann) of Allah.',
    tafsirSourceAr: 'تفسير الطبري',
    tafsirSourceEn: 'Tafsir Al-Tabari',
    audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/1682.mp3',
    tagsAr: ['الدعاء', 'الافتقار', 'حسن الظن', 'قصص الأنبياء'],
    tagsEn: ['Deep Sorrow', 'Tawakkul', 'Prophets', 'Husn al-Dhann'],
    tags: ['Deep Sorrow', 'Tawakkul', 'Prophets'],
    contextAndTakeaway: 'Venting sorrow to Allah in private prayer is the pinnacle of devotion and strength.',
    tafsirSummary: 'Maintaining unwavering good opinion of Allah brings certainty in His relief.',
  },

  // 2. Anxiety & Peace of Mind / السكينة وطمأنينة القلب
  {
    id: 'ref-4',
    categoryId: 'anxiety-peace',
    surahNumber: 13,
    surahNameAr: 'الرعد',
    surahNameEn: 'Ar-Ra\'d',
    ayahNumber: 28,
    ayahTextAr: 'الَّذِينَ آمَنُوا وَتَطْمَئِنُّ قُلُوبُهُم بِذِكْرِ اللَّهِ ۗ أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
    ayahTranslationEn: 'Those who have believed and whose hearts are assured by the remembrance of Allah. Unquestionably, by the remembrance of Allah hearts are assured.',
    ayahMeaningAr: '{تطمئن}: تسكن وتستقر وتزول عنها الوحشة والاضطراب؛ بذكر الله تعالى وتلاوة آياته ومناجاته.',
    contextAndTakeawayAr: 'القلب مخلوق لا يسكن لقلق الدنيا وملهياتها؛ شفاؤه الوحيد هو الاتصال بخالقه. جلسة حفظ وتلاوة بخشوع كفيلة بتبديد أعاصير القلق الداخلي.',
    contextAndTakeawayEn: 'The human heart is engineered to find true equilibrium only when connected to its Maker through Dhikr, Tilawah, and contemplative stillness.',
    tafsirSummaryAr: 'قال ابن كثير: أي يطيب قلب المؤمن عند ذكر الله، ويركن إلى جانبه، وتسكن نفسه عند عظمته، فإنه حقيق ألا يطمئن إلا إليه ولا يفزع إلا إليه.',
    tafsirSummaryEn: 'Hearts become tranquil and serene when remembering Allah, shedding racing anxieties as they settle upon His eternal promises and omnipotence.',
    tafsirSourceAr: 'تفسير ابن كثير',
    tafsirSourceEn: 'Tafsir Ibn Kathir',
    audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/1735.mp3',
    tagsAr: ['ذكر الله', 'الطمأنينة', 'السكينة', 'علاج القلق'],
    tagsEn: ['Inner Peace', 'Dhikr', 'Calmness', 'Mental Health'],
    tags: ['Inner Peace', 'Dhikr', 'Calmness'],
    contextAndTakeaway: 'The heart finds true equilibrium when connected to its Maker through Dhikr and Quran.',
    tafsirSummary: 'Believers find rest and tranquility in Allah\'s remembrance over worldly distractions.',
  },
  {
    id: 'ref-5',
    categoryId: 'anxiety-peace',
    surahNumber: 20,
    surahNameAr: 'طه',
    surahNameEn: 'Ta-Ha',
    ayahNumber: 46,
    ayahTextAr: 'قَالَ لَا تَخَافَا ۖ إِنَّنِي مَعَكُمَا أَسْمَعُ وَأَرَىٰ',
    ayahTranslationEn: 'He said, "Fear not. Indeed, I am with you both; I hear and I see."',
    ayahMeaningAr: 'المعية الخاصة من الله لأوليائه ورسله: حفظ، ورعاية، وتأييد، ونصرة، وإحاطة تامة بكل حركة وسكون.',
    contextAndTakeawayAr: 'مهما تعاظمت التحديات أمامك وبدت قوة الخصم أو ثقل المهمة مرعبة؛ استشعر معية الله ونظره إليك؛ فمن كان الله معه فممن يخاف؟',
    contextAndTakeawayEn: 'Addressed to Musa and Harun before confronting tyrant Pharaoh—when you feel vulnerable, remember Allah\'s watchful, immediate companionship (Ma\'iyyah).',
    tafsirSummaryAr: 'قال السعدي: هذه معية خاصة تقتضي الحفظ والنصرة والتأييد، فلا تخافا من بطش فرعون ولا سطوته؛ فإن ناصيته بيدي ولا ينطق إلا بإذني.',
    tafsirSummaryEn: 'Allah\'s special company with the righteous means preservation, guidance, victory, and divine oversight that diminishes any human threat.',
    tafsirSourceAr: 'تفسير السعدي',
    tafsirSourceEn: 'Tafsir Al-Sa\'di',
    audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/2494.mp3',
    tagsAr: ['معية الله', 'الشجاعة', 'نفي الخوف', 'التأييد الإلهي'],
    tagsEn: ['Courage', 'Overcoming Fear', 'Divine Presence', 'Tawakkul'],
    tags: ['Courage', 'Overcoming Fear', 'Divine Presence'],
    contextAndTakeaway: 'When feeling vulnerable, remember Allah\'s immediate and watchful guardianship.',
    tafsirSummary: 'Divine accompaniment guarantees protection and support against all worldly fears.',
  },
  {
    id: 'ref-6',
    categoryId: 'anxiety-peace',
    surahNumber: 48,
    surahNameAr: 'الفتح',
    surahNameEn: 'Al-Fath',
    ayahNumber: 4,
    ayahTextAr: 'هُوَ الَّذِي أَنزَلَ السَّكِينَةَ فِي قُلُوبِ الْمُؤْمِنِينَ لِيَزْدَادُوا إِيمَانًا مَّعَ إِيمَانِهِمْ',
    ayahTranslationEn: 'It is He who sent down tranquility into the hearts of the believers that they would increase in faith along with their [present] faith.',
    ayahMeaningAr: '{السكينة}: الطمأنينة والوقار والهدوء الذي ينزله الله في قلب عبده عند ورود المخاوف والمحن.',
    contextAndTakeawayAr: 'السكينة ليست جهداً بشرياً بحتاً، بل رزق ومنحة ينزلها الله في أحلك الأوقات ليثبت بها قلوب الصادقين في مواجهة الشدائد.',
    contextAndTakeawayEn: 'Sakina (Divine Tranquility) is a gift sent down in moments of intense uncertainty to shield the heart from panic.',
    tafsirSummaryAr: 'قال القرطبي: أنزل الثبات واليقين في قلوب المؤمنين يوم الحديبية، فرضوا بما أمرهم به رسول الله ﷺ واستقرت نفوسهم وتضاعف إيمانهم.',
    tafsirSummaryEn: 'Tranquility settles inner turmoil during critical milestones, allowing believers to act with deliberate wisdom and steadfast faith.',
    tafsirSourceAr: 'تفسير القرطبي',
    tafsirSourceEn: 'Tafsir Al-Qurtubi',
    audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/4587.mp3',
    tagsAr: ['السكينة', 'زيادة الإيمان', 'الثبات', 'التسليم'],
    tagsEn: ['Tranquility', 'Faith Boost', 'Crisis Management', 'Inner Strength'],
    tags: ['Tranquility', 'Faith Boost', 'Crisis Management'],
    contextAndTakeaway: 'Divine tranquility shields the faithful heart from panic during pivotal milestones.',
    tafsirSummary: 'Tranquility settles the soul so believers act with unwavering wisdom and conviction.',
  },

  // 3. Repentance & Hope / التوبة والرجاء
  {
    id: 'ref-7',
    categoryId: 'repentance-hope',
    surahNumber: 39,
    surahNameAr: 'الزمر',
    surahNameEn: 'Az-Zumar',
    ayahNumber: 53,
    ayahTextAr: 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنفُسِهِمْ لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا ۚ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ',
    ayahTranslationEn: 'Say, "O My servants who have transgressed against themselves [by sinning], do not despair of the mercy of Allah. Indeed, Allah forgives all sins. Indeed, it is He who is the Forgiving, the Merciful."',
    ayahMeaningAr: '{أسرفوا}: أكثروا من المعاصي والذنوب؛ {لا تقنطوا}: لا تيأسوا من مغفرته ورحمته فإنها تسع كل شيء.',
    contextAndTakeawayAr: 'أرجى آية في كتاب الله؛ لاحظ كيف نسبهم الله إليه بلفظ التكريم والتحبب (يا عبادي) رغم إسرافهم. لا تجعل ذنبك حجاباً عن الإقبال على القرآن ومحراب التوبة.',
    contextAndTakeawayEn: 'Known as the most hopeful verse in the entire Quran. Notice how Allah still addresses sinners warmly as "O My servants" (يا عبادي).',
    tafsirSummaryAr: 'قال ابن عباس: هذه الآية نزلت في أناس أصابوا ذنوباً عظيمة فظنوا ألا توبة لهم، فبين الله أن التوبة الصادقة تجب ما قبلها وتمحو الذنوب كأن لم تكن.',
    tafsirSummaryEn: 'Ibn Abbas narrated: This ayah was revealed for those who believed their transgressions were too severe to be forgiven. Sincere repentance erases all previous shortcomings unconditionally.',
    tafsirSourceAr: 'تفسير ابن كثير',
    tafsirSourceEn: 'Tafsir Ibn Kathir',
    audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/4111.mp3',
    tagsAr: ['التوبة', 'سعة الرحمة', 'الرجاء', 'مغفرة الذنوب'],
    tagsEn: ['Tawbah', 'Ultimate Hope', 'Mercy', 'Forgiveness'],
    tags: ['Tawbah', 'Ultimate Hope', 'Mercy', 'Forgiveness'],
    contextAndTakeaway: 'No matter past shortcomings, sincere repentance erases past mistakes unconditionally.',
    tafsirSummary: 'This verse offers the ultimate invitation to return to Allah without hesitation.',
  },
  {
    id: 'ref-8',
    categoryId: 'repentance-hope',
    surahNumber: 25,
    surahNameAr: 'الفرقان',
    surahNameEn: 'Al-Furqan',
    ayahNumber: 70,
    ayahTextAr: 'إِلَّا مَن تَابَ وَآمَنَ وَعَمِلَ عَمَلًا صَالِحًا فَأُولَٰئِكَ يُبَدِّلُ اللَّهُ سَيِّئَاتِهِمْ حَسَنَاتٍ ۗ وَكَانَ اللَّهُ غَفُورًا رَّحِيمًا',
    ayahTranslationEn: 'Except for those who repent, believe and do righteous work. For them Allah will replace their evil deeds with good. And ever is Allah Forgiving and Merciful.',
    ayahMeaningAr: '{يبدل الله سيئاتهم حسنات}: كرم إلهي مضاعف؛ لا يكتفي بمحو الخطيئة بل يقلب رصيد السيئات إلى حسنات مضيئة.',
    contextAndTakeawayAr: 'كرم الله لا حدود له؛ حين تندم بصدق وتتبع التوبة بحفظ القرآن والعمل الصالح، ينقلب ماضيك المعتم إلى رصيد من النور والأجر العظيم.',
    contextAndTakeawayEn: 'Allah does not merely wipe the slate clean—He miraculously converts remorseful past mistakes into a mountain of good deeds.',
    tafsirSummaryAr: 'قال الحسن البصري: يبدلهم الله بالعمل السيئ العمل الصالح، وبالشرك الإخلاص، وبالفجور العفة؛ وقيل: تبدل نفس السيئات التي مضت بحسنات يوم القيامة بحسن التوبة.',
    tafsirSummaryEn: 'True repentance combined with active good deeds transforms previous sins into rewards, demonstrating the boundless generosity of the Most Merciful.',
    tafsirSourceAr: 'تفسير البغوي',
    tafsirSourceEn: 'Tafsir Al-Baghawi',
    audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/2925.mp3',
    tagsAr: ['تبديل السيئات', 'فضل التوبة', 'العمل الصالح', 'الكرم الإلهي'],
    tagsEn: ['Redemption', 'Transformation', 'Mercy', 'Good Deeds'],
    tags: ['Redemption', 'Transformation', 'Mercy'],
    contextAndTakeaway: 'Sincere repentance followed by righteous action converts past shortcomings into rewards.',
    tafsirSummary: 'Divine generosity replaces bad deeds with good ones upon genuine turning back.',
  },

  // 4. Guidance & Purpose / الهداية والتوكل
  {
    id: 'ref-9',
    categoryId: 'guidance-purpose',
    surahNumber: 65,
    surahNameAr: 'الطلاق',
    surahNameEn: 'At-Talaq',
    ayahNumber: 2,
    ayahTextAr: 'وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا ۝ وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ ۚ وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ ۚ إِنَّ اللَّهَ بَالِغُ أَمْرِهِ ۚ قَدْ جَعَلَ اللَّهُ لِكُلِّ شَيْءٍ قَدْرًا',
    ayahTranslationEn: 'And whoever fears Allah - He will make for him a way out, and will provide for him from where he does not expect. And whoever relies upon Allah - then He is sufficient for him. Indeed, Allah will accomplish His purpose. Allah has already set for everything a [decreed] extent.',
    ayahMeaningAr: '{مخرجاً}: خلاصاً من كل ضيق وكربة؛ {فهو حسبه}: كافيه وواقيه ومعينه في كل شأنه.',
    contextAndTakeawayAr: 'حين تنغلق الأبواب الدنيوية في وجهك، تذكر أن مفتاح الفرج هو التقوى وصدق التوكل؛ سيرزقك الله حفظ كتابه وفتح شؤونك من جهة لم تكن في حسبانك.',
    contextAndTakeawayEn: 'When all worldly doors appear locked, Taqwa and sincere Tawakkul unlock unseen avenues of sustenance, provision, and divine solutions.',
    tafsirSummaryAr: 'قال ابن مسعود: هذه أعظم آية تفريجاً في القرآن؛ فمن اتقى الله في أوامره ونواهيه جعل له مخرجاً من مضايق الدنيا والآخرة ورزقه من حيث لا يخطر بباله.',
    tafsirSummaryEn: 'Ibn Mas\'ud noted this is among the greatest verses of relief: Whoever fulfills Taqwa finds divine exits from all earthly and spiritual bottlenecks.',
    tafsirSourceAr: 'تفسير ابن كثير',
    tafsirSourceEn: 'Tafsir Ibn Kathir',
    audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/5221.mp3',
    tagsAr: ['التقوى', 'التوكل', 'الرزق', 'انفراج الكرب'],
    tagsEn: ['Tawakkul', 'Provision', 'Breakthrough', 'Taqwa'],
    tags: ['Tawakkul', 'Provision', 'Breakthrough'],
    contextAndTakeaway: 'Taqwa and sincere trust in Allah open doors of divine provision beyond imagination.',
    tafsirSummary: 'Complete reliance on Allah delivers exit routes from both worldly and spiritual challenges.',
  },
  {
    id: 'ref-10',
    categoryId: 'guidance-purpose',
    surahNumber: 29,
    surahNameAr: 'العنكبوت',
    surahNameEn: 'Al-Ankabut',
    ayahNumber: 69,
    ayahTextAr: 'وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا ۚ وَإِنَّ اللَّهَ لَمَعَ الْمُحْسِنِينَ',
    ayahTranslationEn: 'And those who strive for Us - We will surely guide them to Our ways. And indeed, Allah is with the doers of good.',
    ayahMeaningAr: '{جاهدوا فينا}: بذلوا وسعهم في طاعة الله ومجاهدة النفس والهوى والكسل؛ {لنهدينهم}: لنثبتنهم ونوفقهم لطريق الحق والصواب.',
    contextAndTakeawayAr: 'حفظ القرآن يحتاج مجاهدة وصبر ومغالبة لفتور النفس؛ والوعد الإلهي قطعي: من بذل وسعه مخلصاً هداه الله وسدد لسانه وفتح عليه أبواب الفهم والتثبيت.',
    contextAndTakeawayEn: 'Guidance and mastery in Quran memorization require daily striving (Jihad an-Nafs). The promise is clear: sincere effort guarantees divine navigation.',
    tafsirSummaryAr: 'قال السعدي: كل من بذل جهده في طلب العلم والقرآن والعمل الصالح، هداه الله إلى أسباب الوصول وفتح له من العلوم والمعارف ما لم يكن يحتسب.',
    tafsirSummaryEn: 'Whoever exerts continuous striving in memorization, worship, and overcoming procrastination will be shown illuminated pathways of wisdom and steadfastness.',
    tafsirSourceAr: 'تفسير السعدي',
    tafsirSourceEn: 'Tafsir Al-Sa\'di',
    audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/3409.mp3',
    tagsAr: ['المجاهدة', 'الهداية', 'الإحسان', 'عزيمة الحفظ'],
    tagsEn: ['Striving', 'Hifz Motivation', 'Divine Guidance', 'Ihsan'],
    tags: ['Striving', 'Hifz Motivation', 'Divine Guidance'],
    contextAndTakeaway: 'Sincere daily striving in memorizing Allah\'s book guarantees divine ease and guidance.',
    tafsirSummary: 'Continuous dedication to sacred knowledge unlocks understanding and spiritual mastery.',
  },

  // 5. Quran Companionship & Hifz Devotion / بركة القرآن وفضل الحفظ
  {
    id: 'ref-11',
    categoryId: 'quran-striving',
    surahNumber: 54,
    surahNameAr: 'القمر',
    surahNameEn: 'Al-Qamar',
    ayahNumber: 17,
    ayahTextAr: 'وَلَقَدْ يَسَّرْنَا الْقُرْآنَ لِلذِّكْرِ فَهَلْ مِن مُّدَّكِرٍ',
    ayahTranslationEn: 'And We have certainly made the Quran easy for remembrance, so is there any who will remember?',
    ayahMeaningAr: '{يسرنا}: سهلنا ألفاظه للحفظ والتلاوة، ومعانيه للفهم والتدبر؛ {مدكر}: متعظ ومقبل على حفظه وتدبره.',
    contextAndTakeawayAr: 'تطمين إلهي لكل مقبل على الحفظ: القرآن ميسر بأمر الله، ليس عسيراً على من صدقت نيته. كل ما تحتاجه هو خطوة إقبال وإخلاص، وسيتكفل الله بالتيسير.',
    contextAndTakeawayEn: 'A divine reassurance for every memorizer: the Quran has been facilitated for retention and reflection. All that is required is sincere commitment.',
    tafsirSummaryAr: 'قال مجاهد: يسرناه أي سهلنا تلاوته وحفظه في الصدور، فهل من طالب علم فيعان عليه؟ وقال مطر الوراق: هل من طالب خير فيعان عليه؟',
    tafsirSummaryEn: 'Mujahid said: Allah made the Quran easy to recite, memorize in chests, and understand. Whoever steps forward to learn and preserve it will receive divine aid.',
    tafsirSourceAr: 'تفسير الطبري',
    tafsirSourceEn: 'Tafsir Al-Tabari',
    audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/4863.mp3',
    tagsAr: ['تيسير القرآن', 'الحفظ', 'التذكر', 'البركة'],
    tagsEn: ['Facilitation', 'Hifz Ease', 'Remembrance', 'Encouragement'],
    tags: ['Facilitation', 'Hifz Ease', 'Remembrance'],
    contextAndTakeaway: 'The Quran is divinely facilitated for memorization for anyone with a sincere heart.',
    tafsirSummary: 'Allah facilitates memorization and comprehension for those who seek to learn His words.',
  },
  {
    id: 'ref-12',
    categoryId: 'quran-striving',
    surahNumber: 35,
    surahNameAr: 'فاطر',
    surahNameEn: 'Fatir',
    ayahNumber: 29,
    ayahTextAr: 'إِنَّ الَّذِينَ يَتْلُونَ كِتَابَ اللَّهِ وَأَقَامُوا الصَّلَاةَ وَأَنفَقُوا مِمَّا رَزَقْنَاهُمْ سِرًّا وَعَلَانِيَةً يَرْجُونَ تِجَارَةً لَّن تَبُورَ ۝ لِيُوَفِّيَهُمْ أُجُورَهُمْ وَيَزِيدَهُم مِّن فَضْلِهِ ۚ إِنَّهُ غَفُورٌ شَكُورٌ',
    ayahTranslationEn: 'Indeed, those who recite the Book of Allah and establish prayer and spend out of what We have provided them, secretly and publicly, [can] expect a transaction that will never perish - That He may give them in full their rewards and increase for them of His bounty. Indeed, He is Forgiving and Appreciative.',
    ayahMeaningAr: '{تجارة لن تبور}: تجارة رابحة مضمونة لا تعرف الخسارة أو الكساد أبداً مع ملك الملوك سبحانه.',
    contextAndTakeawayAr: 'دقائقك وساعاتك التي تقضيها مع شريكك في مراجعة وتسميع وتدبر القرآن هي أعظم استثمار وتجارة رابحة في الدنيا والآخرة لا تعرف الخسارة أبداً.',
    contextAndTakeawayEn: 'Your daily commitment with your partner in reciting and reviewing the Quran is the ultimate non-perishing transaction with the King of Kings.',
    tafsirSummaryAr: 'قال قتادة: كان مطرف بن عبد الله إذا قرأ هذه الآية قال: هذه آية القراء؛ بين الله أن تلاوة القرآن وتدبره والعمل به تجارة رابحة موفورة الأجر والزيادة في الدنيا والآخرة.',
    tafsirSummaryEn: 'Qatadah related that this is "The verse of the Quran reciters." Devoting oneself to the Quran guarantees full reward and abundant multiplied divine grace.',
    tafsirSourceAr: 'تفسير ابن كثير',
    tafsirSourceEn: 'Tafsir Ibn Kathir',
    audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/3689.mp3',
    tagsAr: ['تجارة لن تبور', 'أهل القرآن', 'فضل التلاوة', 'الأجر المضاعف'],
    tagsEn: ['Everlasting Trade', 'Quran Companions', 'Abundant Bounty', 'Hifz Rewards'],
    tags: ['Everlasting Trade', 'Quran Companions', 'Abundant Bounty'],
    contextAndTakeaway: 'Devoting time to the Quran with your partner is an eternal, thriving investment with Allah.',
    tafsirSummary: 'Reciters and memorizers of the Book receive their full reward and overflowing bounty.',
  },
];

// Complete 114 Surahs catalog with Arabic names, pages, and metadata
export const SURAH_CATALOG: SurahMeta[] = [
  { number: 1, name: 'الفاتحة', englishName: 'Al-Faatiha', englishNameTranslation: 'The Opening', numberOfAyahs: 7, revelationType: 'Meccan', startPage: 1, endPage: 1 },
  { number: 2, name: 'البقرة', englishName: 'Al-Baqarah', englishNameTranslation: 'The Cow', numberOfAyahs: 286, revelationType: 'Medinan', startPage: 2, endPage: 49 },
  { number: 3, name: 'آل عمران', englishName: 'Aal-i-Imraan', englishNameTranslation: 'Family of Imran', numberOfAyahs: 200, revelationType: 'Medinan', startPage: 50, endPage: 76 },
  { number: 4, name: 'النساء', englishName: 'An-Nisaa', englishNameTranslation: 'The Women', numberOfAyahs: 176, revelationType: 'Medinan', startPage: 77, endPage: 106 },
  { number: 5, name: 'المائدة', englishName: 'Al-Maaida', englishNameTranslation: 'The Table Spread', numberOfAyahs: 120, revelationType: 'Medinan', startPage: 106, endPage: 127 },
  { number: 6, name: 'الأنعام', englishName: 'Al-An\'aam', englishNameTranslation: 'The Cattle', numberOfAyahs: 165, revelationType: 'Meccan', startPage: 128, endPage: 150 },
  { number: 7, name: 'الأعراف', englishName: 'Al-A\'raaf', englishNameTranslation: 'The Heights', numberOfAyahs: 206, revelationType: 'Meccan', startPage: 151, endPage: 176 },
  { number: 8, name: 'الأنفال', englishName: 'Al-Anfaal', englishNameTranslation: 'The Spoils of War', numberOfAyahs: 75, revelationType: 'Medinan', startPage: 177, endPage: 186 },
  { number: 9, name: 'التوبة', englishName: 'At-Tawba', englishNameTranslation: 'The Repentance', numberOfAyahs: 129, revelationType: 'Medinan', startPage: 187, endPage: 207 },
  { number: 10, name: 'يونس', englishName: 'Yunus', englishNameTranslation: 'Jonah', numberOfAyahs: 109, revelationType: 'Meccan', startPage: 208, endPage: 221 },
  { number: 11, name: 'هود', englishName: 'Hud', englishNameTranslation: 'Hud', numberOfAyahs: 123, revelationType: 'Meccan', startPage: 221, endPage: 235 },
  { number: 12, name: 'يوسف', englishName: 'Yusuf', englishNameTranslation: 'Joseph', numberOfAyahs: 111, revelationType: 'Meccan', startPage: 235, endPage: 248 },
  { number: 13, name: 'الرعد', englishName: 'Ar-Ra\'d', englishNameTranslation: 'The Thunder', numberOfAyahs: 43, revelationType: 'Medinan', startPage: 249, endPage: 255 },
  { number: 14, name: 'إبراهيم', englishName: 'Ibrahim', englishNameTranslation: 'Abraham', numberOfAyahs: 52, revelationType: 'Meccan', startPage: 255, endPage: 261 },
  { number: 15, name: 'الحجر', englishName: 'Al-Hijr', englishNameTranslation: 'The Rocky Tract', numberOfAyahs: 99, revelationType: 'Meccan', startPage: 262, endPage: 267 },
  { number: 16, name: 'النحل', englishName: 'An-Nahl', englishNameTranslation: 'The Bee', numberOfAyahs: 128, revelationType: 'Meccan', startPage: 267, endPage: 281 },
  { number: 17, name: 'الإسراء', englishName: 'Al-Israa', englishNameTranslation: 'The Night Journey', numberOfAyahs: 111, revelationType: 'Meccan', startPage: 282, endPage: 293 },
  { number: 18, name: 'الكهف', englishName: 'Al-Kahf', englishNameTranslation: 'The Cave', numberOfAyahs: 110, revelationType: 'Meccan', startPage: 293, endPage: 304 },
  { number: 19, name: 'مريم', englishName: 'Maryam', englishNameTranslation: 'Mary', numberOfAyahs: 98, revelationType: 'Meccan', startPage: 305, endPage: 312 },
  { number: 20, name: 'طه', englishName: 'Taa-Haa', englishNameTranslation: 'Ta-Ha', numberOfAyahs: 135, revelationType: 'Meccan', startPage: 312, endPage: 321 },
  { number: 21, name: 'الأنبياء', englishName: 'Al-Anbiyaa', englishNameTranslation: 'The Prophets', numberOfAyahs: 112, revelationType: 'Meccan', startPage: 322, endPage: 331 },
  { number: 22, name: 'الحج', englishName: 'Al-Hajj', englishNameTranslation: 'The Pilgrimage', numberOfAyahs: 78, revelationType: 'Medinan', startPage: 332, endPage: 341 },
  { number: 23, name: 'المؤمنون', englishName: 'Al-Mu\'minoon', englishNameTranslation: 'The Believers', numberOfAyahs: 118, revelationType: 'Meccan', startPage: 342, endPage: 349 },
  { number: 24, name: 'النور', englishName: 'An-Noor', englishNameTranslation: 'The Light', numberOfAyahs: 64, revelationType: 'Medinan', startPage: 350, endPage: 359 },
  { number: 25, name: 'الفرقان', englishName: 'Al-Furqaan', englishNameTranslation: 'The Criterion', numberOfAyahs: 77, revelationType: 'Meccan', startPage: 359, endPage: 366 },
  { number: 26, name: 'الشعراء', englishName: 'Ash-Shu\'araa', englishNameTranslation: 'The Poets', numberOfAyahs: 227, revelationType: 'Meccan', startPage: 367, endPage: 376 },
  { number: 27, name: 'النمل', englishName: 'An-Naml', englishNameTranslation: 'The Ant', numberOfAyahs: 93, revelationType: 'Meccan', startPage: 377, endPage: 385 },
  { number: 28, name: 'القصص', englishName: 'Al-Qasas', englishNameTranslation: 'The Stories', numberOfAyahs: 88, revelationType: 'Meccan', startPage: 385, endPage: 396 },
  { number: 29, name: 'العنكبوت', englishName: 'Al-Ankaboot', englishNameTranslation: 'The Spider', numberOfAyahs: 69, revelationType: 'Meccan', startPage: 396, endPage: 404 },
  { number: 30, name: 'الروم', englishName: 'Ar-Room', englishNameTranslation: 'The Romans', numberOfAyahs: 60, revelationType: 'Meccan', startPage: 404, endPage: 410 },
  { number: 31, name: 'لقمان', englishName: 'Luqman', englishNameTranslation: 'Luqman', numberOfAyahs: 34, revelationType: 'Meccan', startPage: 411, endPage: 414 },
  { number: 32, name: 'السجدة', englishName: 'As-Sajda', englishNameTranslation: 'The Prostration', numberOfAyahs: 30, revelationType: 'Meccan', startPage: 415, endPage: 417 },
  { number: 33, name: 'الأحزاب', englishName: 'Al-Ahzaab', englishNameTranslation: 'The Combined Forces', numberOfAyahs: 73, revelationType: 'Medinan', startPage: 418, endPage: 427 },
  { number: 34, name: 'سبأ', englishName: 'Saba', englishNameTranslation: 'Sheba', numberOfAyahs: 54, revelationType: 'Meccan', startPage: 428, endPage: 434 },
  { number: 35, name: 'فاطر', englishName: 'Faatir', englishNameTranslation: 'The Originator', numberOfAyahs: 45, revelationType: 'Meccan', startPage: 434, endPage: 440 },
  { number: 36, name: 'يس', englishName: 'Yaseen', englishNameTranslation: 'Yasin', numberOfAyahs: 83, revelationType: 'Meccan', startPage: 440, endPage: 445 },
  { number: 37, name: 'الصافات', englishName: 'As-Saaffaat', englishNameTranslation: 'Those who set the Ranks', numberOfAyahs: 182, revelationType: 'Meccan', startPage: 446, endPage: 452 },
  { number: 38, name: 'ص', englishName: 'Saad', englishNameTranslation: 'The Letter Saad', numberOfAyahs: 88, revelationType: 'Meccan', startPage: 453, endPage: 458 },
  { number: 39, name: 'الزمر', englishName: 'Az-Zumar', englishNameTranslation: 'The Troops', numberOfAyahs: 75, revelationType: 'Meccan', startPage: 458, endPage: 467 },
  { number: 40, name: 'غافر', englishName: 'Ghafir', englishNameTranslation: 'The Forgiver', numberOfAyahs: 85, revelationType: 'Meccan', startPage: 467, endPage: 476 },
  { number: 41, name: 'فصلت', englishName: 'Fussilat', englishNameTranslation: 'Explained in Detail', numberOfAyahs: 54, revelationType: 'Meccan', startPage: 477, endPage: 482 },
  { number: 42, name: 'الشورى', englishName: 'Ash-Shura', englishNameTranslation: 'The Consultation', numberOfAyahs: 53, revelationType: 'Meccan', startPage: 483, endPage: 489 },
  { number: 43, name: 'الزخرف', englishName: 'Az-Zukhruf', englishNameTranslation: 'The Ornaments of Gold', numberOfAyahs: 89, revelationType: 'Meccan', startPage: 489, endPage: 495 },
  { number: 44, name: 'الدخان', englishName: 'Ad-Dukhaan', englishNameTranslation: 'The Smoke', numberOfAyahs: 59, revelationType: 'Meccan', startPage: 496, endPage: 498 },
  { number: 45, name: 'الجاثية', englishName: 'Al-Jaathiya', englishNameTranslation: 'The Crouching', numberOfAyahs: 37, revelationType: 'Meccan', startPage: 499, endPage: 502 },
  { number: 46, name: 'الأحقاف', englishName: 'Al-Ahqaaf', englishNameTranslation: 'The Wind-Curved Sandhills', numberOfAyahs: 35, revelationType: 'Meccan', startPage: 502, endPage: 506 },
  { number: 47, name: 'محمد', englishName: 'Muhammad', englishNameTranslation: 'Muhammad', numberOfAyahs: 38, revelationType: 'Medinan', startPage: 507, endPage: 510 },
  { number: 48, name: 'الفتح', englishName: 'Al-Fath', englishNameTranslation: 'The Victory', numberOfAyahs: 29, revelationType: 'Medinan', startPage: 511, endPage: 515 },
  { number: 49, name: 'الحجرات', englishName: 'Al-Hujuraat', englishNameTranslation: 'The Rooms', numberOfAyahs: 18, revelationType: 'Medinan', startPage: 515, endPage: 517 },
  { number: 50, name: 'ق', englishName: 'Qaaf', englishNameTranslation: 'The Letter Qaf', numberOfAyahs: 45, revelationType: 'Meccan', startPage: 518, endPage: 520 },
  { number: 51, name: 'الذاريات', englishName: 'Adh-Dhaariyat', englishNameTranslation: 'The Winnowing Winds', numberOfAyahs: 60, revelationType: 'Meccan', startPage: 520, endPage: 523 },
  { number: 52, name: 'الطور', englishName: 'At-Toor', englishNameTranslation: 'The Mount', numberOfAyahs: 49, revelationType: 'Meccan', startPage: 523, endPage: 525 },
  { number: 53, name: 'النجم', englishName: 'An-Najm', englishNameTranslation: 'The Star', numberOfAyahs: 62, revelationType: 'Meccan', startPage: 526, endPage: 528 },
  { number: 54, name: 'القمر', englishName: 'Al-Qamar', englishNameTranslation: 'The Moon', numberOfAyahs: 55, revelationType: 'Meccan', startPage: 528, endPage: 531 },
  { number: 55, name: 'الرحمن', englishName: 'Ar-Rahmaan', englishNameTranslation: 'The Beneficent', numberOfAyahs: 78, revelationType: 'Medinan', startPage: 531, endPage: 534 },
  { number: 56, name: 'الواقعة', englishName: 'Al-Waaqia', englishNameTranslation: 'The Inevitable', numberOfAyahs: 96, revelationType: 'Meccan', startPage: 534, endPage: 537 },
  { number: 57, name: 'الحديد', englishName: 'Al-Hadid', englishNameTranslation: 'The Iron', numberOfAyahs: 29, revelationType: 'Medinan', startPage: 537, endPage: 541 },
  { number: 58, name: 'المجادلة', englishName: 'Al-Mujaadila', englishNameTranslation: 'The Pleading Woman', numberOfAyahs: 22, revelationType: 'Medinan', startPage: 542, endPage: 545 },
  { number: 59, name: 'الحشر', englishName: 'Al-Hashr', englishNameTranslation: 'The Exile', numberOfAyahs: 24, revelationType: 'Medinan', startPage: 545, endPage: 548 },
  { number: 60, name: 'الممتحنة', englishName: 'Al-Mumtahana', englishNameTranslation: 'She that is to be examined', numberOfAyahs: 13, revelationType: 'Medinan', startPage: 549, endPage: 551 },
  { number: 61, name: 'الصف', englishName: 'As-Saff', englishNameTranslation: 'The Ranks', numberOfAyahs: 14, revelationType: 'Medinan', startPage: 551, endPage: 552 },
  { number: 62, name: 'الجمعة', englishName: 'Al-Jumu\'a', englishNameTranslation: 'The Congregation', numberOfAyahs: 11, revelationType: 'Medinan', startPage: 553, endPage: 554 },
  { number: 63, name: 'المنافقون', englishName: 'Al-Munaafiqoon', englishNameTranslation: 'The Hypocrites', numberOfAyahs: 11, revelationType: 'Medinan', startPage: 554, endPage: 555 },
  { number: 64, name: 'التغابن', englishName: 'At-Taghaabun', englishNameTranslation: 'The Mutual Disillusion', numberOfAyahs: 18, revelationType: 'Medinan', startPage: 556, endPage: 557 },
  { number: 65, name: 'الطلاق', englishName: 'At-Talaaq', englishNameTranslation: 'The Divorce', numberOfAyahs: 12, revelationType: 'Medinan', startPage: 558, endPage: 559 },
  { number: 66, name: 'التحريم', englishName: 'At-Tahrim', englishNameTranslation: 'The Prohibition', numberOfAyahs: 12, revelationType: 'Medinan', startPage: 560, endPage: 561 },
  { number: 67, name: 'الملك', englishName: 'Al-Mulk', englishNameTranslation: 'The Sovereignty', numberOfAyahs: 30, revelationType: 'Meccan', startPage: 562, endPage: 564 },
  { number: 68, name: 'القلم', englishName: 'Al-Qalam', englishNameTranslation: 'The Pen', numberOfAyahs: 52, revelationType: 'Meccan', startPage: 564, endPage: 566 },
  { number: 69, name: 'الحاقة', englishName: 'Al-Haaqqa', englishNameTranslation: 'The Reality', numberOfAyahs: 52, revelationType: 'Meccan', startPage: 566, endPage: 568 },
  { number: 70, name: 'المعارج', englishName: 'Al-Ma\'aarij', englishNameTranslation: 'The Ascending Stairways', numberOfAyahs: 44, revelationType: 'Meccan', startPage: 568, endPage: 570 },
  { number: 71, name: 'نوح', englishName: 'Nooh', englishNameTranslation: 'Noah', numberOfAyahs: 28, revelationType: 'Meccan', startPage: 570, endPage: 571 },
  { number: 72, name: 'الجن', englishName: 'Al-Jinn', englishNameTranslation: 'The Jinn', numberOfAyahs: 28, revelationType: 'Meccan', startPage: 572, endPage: 573 },
  { number: 73, name: 'المزمل', englishName: 'Al-Muzzammil', englishNameTranslation: 'The Enshrouded One', numberOfAyahs: 20, revelationType: 'Meccan', startPage: 574, endPage: 575 },
  { number: 74, name: 'المدثر', englishName: 'Al-Muddaththir', englishNameTranslation: 'The Cloaked One', numberOfAyahs: 56, revelationType: 'Meccan', startPage: 575, endPage: 577 },
  { number: 75, name: 'القيامة', englishName: 'Al-Qiyaama', englishNameTranslation: 'The Resurrection', numberOfAyahs: 40, revelationType: 'Meccan', startPage: 577, endPage: 578 },
  { number: 76, name: 'الإنسان', englishName: 'Al-Insaan', englishNameTranslation: 'The Human', numberOfAyahs: 31, revelationType: 'Medinan', startPage: 578, endPage: 580 },
  { number: 77, name: 'المرسلات', englishName: 'Al-Mursalaat', englishNameTranslation: 'The Emissaries', numberOfAyahs: 50, revelationType: 'Meccan', startPage: 580, endPage: 581 },
  { number: 78, name: 'النبأ', englishName: 'An-Naba', englishNameTranslation: 'The Tidings', numberOfAyahs: 40, revelationType: 'Meccan', startPage: 582, endPage: 583 },
  { number: 79, name: 'النازعات', englishName: 'An-Naazi\'aat', englishNameTranslation: 'Those who drag forth', numberOfAyahs: 46, revelationType: 'Meccan', startPage: 583, endPage: 584 },
  { number: 80, name: 'عبس', englishName: 'Abasa', englishNameTranslation: 'He Frowned', numberOfAyahs: 42, revelationType: 'Meccan', startPage: 585, endPage: 586 },
  { number: 81, name: 'التكوير', englishName: 'At-Takweer', englishNameTranslation: 'The Overthrowing', numberOfAyahs: 29, revelationType: 'Meccan', startPage: 586, endPage: 587 },
  { number: 82, name: 'الانفطار', englishName: 'Al-Infitaar', englishNameTranslation: 'The Cleaving', numberOfAyahs: 19, revelationType: 'Meccan', startPage: 587, endPage: 587 },
  { number: 83, name: 'المطففين', englishName: 'Al-Mutaffifin', englishNameTranslation: 'The Defrauding', numberOfAyahs: 36, revelationType: 'Meccan', startPage: 587, endPage: 589 },
  { number: 84, name: 'الانشقاق', englishName: 'Al-Inshiqaaq', englishNameTranslation: 'The Splitting Open', numberOfAyahs: 25, revelationType: 'Meccan', startPage: 589, endPage: 590 },
  { number: 85, name: 'البروج', englishName: 'Al-Burooj', englishNameTranslation: 'The Constellations', numberOfAyahs: 22, revelationType: 'Meccan', startPage: 590, endPage: 591 },
  { number: 86, name: 'الطارق', englishName: 'At-Taariq', englishNameTranslation: 'The Morning Star', numberOfAyahs: 17, revelationType: 'Meccan', startPage: 591, endPage: 591 },
  { number: 87, name: 'الأعلى', englishName: 'Al-A\'laa', englishNameTranslation: 'The Most High', numberOfAyahs: 19, revelationType: 'Meccan', startPage: 591, endPage: 592 },
  { number: 88, name: 'الغاشية', englishName: 'Al-Ghaashiya', englishNameTranslation: 'The Overwhelming', numberOfAyahs: 26, revelationType: 'Meccan', startPage: 592, endPage: 593 },
  { number: 89, name: 'الفجر', englishName: 'Al-Fajr', englishNameTranslation: 'The Dawn', numberOfAyahs: 30, revelationType: 'Meccan', startPage: 593, endPage: 594 },
  { number: 90, name: 'البلد', englishName: 'Al-Balad', englishNameTranslation: 'The City', numberOfAyahs: 20, revelationType: 'Meccan', startPage: 594, endPage: 595 },
  { number: 91, name: 'الشمس', englishName: 'Ash-Shams', englishNameTranslation: 'The Sun', numberOfAyahs: 15, revelationType: 'Meccan', startPage: 595, endPage: 595 },
  { number: 92, name: 'الليل', englishName: 'Al-Lail', englishNameTranslation: 'The Night', numberOfAyahs: 21, revelationType: 'Meccan', startPage: 595, endPage: 596 },
  { number: 93, name: 'الضحى', englishName: 'Ad-Dhuhaa', englishNameTranslation: 'The Morning Hours', numberOfAyahs: 11, revelationType: 'Meccan', startPage: 596, endPage: 596 },
  { number: 94, name: 'الشرح', englishName: 'Ash-Sharh', englishNameTranslation: 'The Relief', numberOfAyahs: 8, revelationType: 'Meccan', startPage: 596, endPage: 596 },
  { number: 95, name: 'التين', englishName: 'At-Teen', englishNameTranslation: 'The Fig', numberOfAyahs: 8, revelationType: 'Meccan', startPage: 596, endPage: 597 },
  { number: 96, name: 'العلق', englishName: 'Al-Alaq', englishNameTranslation: 'The Clot', numberOfAyahs: 19, revelationType: 'Meccan', startPage: 597, endPage: 597 },
  { number: 97, name: 'القدر', englishName: 'Al-Qadr', englishNameTranslation: 'The Power', numberOfAyahs: 5, revelationType: 'Meccan', startPage: 598, endPage: 598 },
  { number: 98, name: 'البينة', englishName: 'Al-Bayyina', englishNameTranslation: 'The Clear Proof', numberOfAyahs: 8, revelationType: 'Medinan', startPage: 598, endPage: 599 },
  { number: 99, name: 'الزلزلة', englishName: 'Az-Zalzala', englishNameTranslation: 'The Earthquake', numberOfAyahs: 8, revelationType: 'Medinan', startPage: 599, endPage: 599 },
  { number: 100, name: 'العاديات', englishName: 'Al-Aadiyaat', englishNameTranslation: 'The Courser', numberOfAyahs: 11, revelationType: 'Meccan', startPage: 599, endPage: 600 },
  { number: 101, name: 'القارعة', englishName: 'Al-Qaari\'a', englishNameTranslation: 'The Calamity', numberOfAyahs: 11, revelationType: 'Meccan', startPage: 600, endPage: 600 },
  { number: 102, name: 'التكاثر', englishName: 'At-Takaathur', englishNameTranslation: 'The Rivalry in world increase', numberOfAyahs: 8, revelationType: 'Meccan', startPage: 600, endPage: 600 },
  { number: 103, name: 'العصر', englishName: 'Al-Asr', englishNameTranslation: 'The Declining Day', numberOfAyahs: 3, revelationType: 'Meccan', startPage: 601, endPage: 601 },
  { number: 104, name: 'الهمزة', englishName: 'Al-Humaza', englishNameTranslation: 'The Traducer', numberOfAyahs: 9, revelationType: 'Meccan', startPage: 601, endPage: 601 },
  { number: 105, name: 'الفيل', englishName: 'Al-Feel', englishNameTranslation: 'The Elephant', numberOfAyahs: 5, revelationType: 'Meccan', startPage: 601, endPage: 601 },
  { number: 106, name: 'قريش', englishName: 'Quraish', englishNameTranslation: 'Quraysh', numberOfAyahs: 4, revelationType: 'Meccan', startPage: 602, endPage: 602 },
  { number: 107, name: 'الماعون', englishName: 'Al-Maa\'oon', englishNameTranslation: 'The Small Kindness', numberOfAyahs: 7, revelationType: 'Meccan', startPage: 602, endPage: 602 },
  { number: 108, name: 'الكوثر', englishName: 'Al-Kawthar', englishNameTranslation: 'The Abundance', numberOfAyahs: 3, revelationType: 'Meccan', startPage: 602, endPage: 602 },
  { number: 109, name: 'الكافرون', englishName: 'Al-Kaafiroon', englishNameTranslation: 'The Disbelievers', numberOfAyahs: 6, revelationType: 'Meccan', startPage: 603, endPage: 603 },
  { number: 110, name: 'النصر', englishName: 'An-Nasr', englishNameTranslation: 'The Divine Support', numberOfAyahs: 3, revelationType: 'Medinan', startPage: 603, endPage: 603 },
  { number: 111, name: 'المسد', englishName: 'Al-Masad', englishNameTranslation: 'The Palm Fiber', numberOfAyahs: 5, revelationType: 'Meccan', startPage: 603, endPage: 603 },
  { number: 112, name: 'الإخلاص', englishName: 'Al-Ikhlaas', englishNameTranslation: 'The Sincerity', numberOfAyahs: 4, revelationType: 'Meccan', startPage: 604, endPage: 604 },
  { number: 113, name: 'الفلق', englishName: 'Al-Falaq', englishNameTranslation: 'The Daybreak', numberOfAyahs: 5, revelationType: 'Meccan', startPage: 604, endPage: 604 },
  { number: 114, name: 'الناس', englishName: 'An-Naas', englishNameTranslation: 'Mankind', numberOfAyahs: 6, revelationType: 'Meccan', startPage: 604, endPage: 604 },
];
